# -*- coding: utf-8 -*-
"""CURRENYconv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T5auZT_IjesFrQlIrstVTH8Ga3oRY-rD
"""

CURRENCIES = {
    'USD': 1,
    'EUR': 1.06,
    'YEN': 0.0067,
    'GBP': 1.23,
    'AUD': 0.64,
    'CAD': 0.74
}

# Write code here
def to_usd(currency,amount):
    if currency not in CURRENCIES.keys():
        raise Exception(f"{currency} is not supported")
    elif amount<0:
        raise Exception("Invalid amount")
    else:
        return amount* CURRENCIES.get(currency)

def from_usd(currency,amount):
    if currency not in CURRENCIES.keys():
        raise Exception(f"{currency} is not supported")
    elif amount<0:
        raise Exception("Invalid amount")
    else:
        return round(amount/ CURRENCIES.get(currency),4)

def convert(FROM,amount,TO):
    try:
        initial_amt=to_usd(FROM,amount)
        finl_amt=from_usd(TO,initial_amt)
        RES= print(float(amount),FROM, "is",finl_amt,TO)
        return RES
    except Exception as e:
        print(e)
convert("EUR",543.12,"GBP")